news_sites:
  vanguardia:
    url: https://www.vanguardia.com/
    queries: 
      homepage_article_links: '.noticias a'
      article_body: '.paragraph'
      article_title: 'h1[itemprop="headline"] .priority-content'
      article_date: 'div[itemprop="datepublished"]'
  antena2:
    url: https://www.antena2.com/
    queries: 
      homepage_article_links: '.title-three a'
      article_body: 'div[property="schema:text"]'
      article_title: '.title-resumen h1'
      article_date: '.box-section-date time'